<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ErrorLog>../../artifacts/diagnostics.executable.sarif</ErrorLog>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="CodeMetricsConfig.txt" />
  </ItemGroup>

</Project>
